stages:
  - prepare
  - build
  - upload
  - release

default:
  image: ubuntu:22.04

workflow:
  rules:
    - if: $CI_COMMIT_TAG

prepare:
  stage: prepare
  script:
    - echo "PKG_REGISTRY_URL=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic" >> variables.env
  artifacts:
    reports:
      dotenv: variables.env

build:
  stage: build
  needs:
    - job: prepare
      artifacts: true
  script:
    - apt update
    - apt install lld clang curl gcc-mingw-w64-x86-64-win32 -y
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    - source "$HOME/.cargo/env"
    - rustup target add x86_64-pc-windows-gnu
    - cargo build --release --target x86_64-unknown-linux-gnu --target x86_64-pc-windows-gnu
    - ls -la target/
    - mkdir bin
    - mkdir bin/e-cli-win/
    - mkdir bin/e-cli-linux/
    - mv target/x86_64-pc-windows-gnu/release/e-cli.exe bin/e-cli-win/
    - mv target/x86_64-unknown-linux-gnu/release/e-cli bin/e-cli-linux/
    - ls -la bin/*
  artifacts:
    when: on_success
    expire_in: "30 days"
    paths:
      - bin/

upload-package:
  stage: upload
  needs:
    - job: prepare
      artifacts: true
    - job: build
      artifacts: true
  script:
    - apt update
    - apt install curl -y
    - ls -la bin/
    - ls -la bin/*
    - 'curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file bin/e-cli-win/e-cli.exe ${PKG_REGISTRY_URL}/x86_64-pc-windows-gnu/${CI_COMMIT_TAG}/e-cli.exe'
    - 'curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file bin/e-cli-linux/e-cli ${PKG_REGISTRY_URL}/x86_64-unknown-linux-gnu/${CI_COMMIT_TAG}/e-cli'

create-release:
  stage: release
  image: registry.gitlab.com/gitlab-org/cli:latest
  needs:
    - job: prepare
      artifacts: true
    - job: build
  script:
    - echo "Creating the release..."
  release:
    tag_name: $CI_COMMIT_TAG
    name: 'Release $CI_COMMIT_TAG'
    description: 'Release created using the Build Pipeline.'
    assets:
      links:
        - name: "e-cli-win_x86_64"
          url: "${PKG_REGISTRY_URL}/x86_64-pc-windows-gnu/${CI_COMMIT_TAG}/e-cli.exe"
        - name: "e-cli-linux_x86_64"
          url: "${PKG_REGISTRY_URL}/x86_64-unknown-linux-gnu/${CI_COMMIT_TAG}/e-cli"

