[package]
name = "e-cli"
version = "0.2.0"
authors = ["Saniee"]
repository = "https://github.com/Saniee/e-cli"
documentation = "https://saniee.github.io/e-cli/"
edition = "2021"


[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
indicatif = { version = "0.17.8", features = ["tokio"] }
rayon = "1.10.0"
serde = { version = "1.0.200", features = ["derive"] }
serde_json = "1.0.116"
ureq = { version = "3.0.12", features = ["json"] }
