name: Release Binaries

on:
  release:
    types:
      - created

jobs:
  linux_windows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Linux and Windows Cross Compilers
        run: sudo apt-get install --yes --no-install-recommends musl-tools gcc-mingw-w64-x86-64-win32\
      - name: Install rustup Targets
        run: rustup target add x86_64-unknown-linux-musl x86_64-pc-windows-gnu
      - name: Build Binaries
        run: cargo build --release --target x86_64-unknown-linux-musl --target x86_64-pc-windows-gnu
      - name: Tar Linux Binary
        run: tar -czvf e-cli-gnu-linux-x86_64.tar.gz -C target/x86_64-unknown-linux-musl/release/e-cli
      - name: Zip Windows Binary
        run: zip -j e-cli-windows.zip target/x86_64-pc-windows-gnu/release/e-cli.exe
      - name: Generate Checksums
        run: |
          shasum -a 256 e-cli-gnu-linux-x86_64.tar.gz > e-cli-gnu-linux-x86_64.tar.gz.sha256
          shasum -a 256 e-cli-windows.zip > e-cli-windows.zip.sha256
      - name: Upload Binaries
        uses: alexellis/upload-assets@0.4.0
        env: 
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["e-cli-gnu-linux-x86_64.tar.gz", "e-cli-windows.zip", "e-cli-gnu-linux-x86_64.tar.gz.sha256", "e-cli-windows.zip.sha256"]'
